queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>0"
      - base~=^Agoric
      - label=automerge
    merge_conditions:
      - base~=^Agoric
    merge_method: merge

pull_request_rules:
  - name: backport patches to Agoric branch
    conditions:
      - base=main
      - label=backport/0.46.x
    actions:
      backport:
        branches:
          - release/v0.46.x
  - name: backport patches to v0.45.x branch
    conditions:
      - base=main
      - label=backport/0.45.x
    actions:
      backport:
        branches:
          - Agoric-ag0
  - name: automerge to Agoric* with label automerge and branch protection passing
    conditions: []
    actions:
      queue:
