name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5 # v5 is broken, ref https://github.com/actions/labeler/issues/712. Do not bump.
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
