name: Lint
on:
  push:
    branches:
      - main
      - release/**
  pull_request:
  merge_group:
permissions:
  contents: read

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17
      - uses: technote-space/get-diff-action@v5
        id: git_diff
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: run go linters
        run: make lint-go
        if: env.GIT_DIFF
        id: lint_long
        run: |
          make lint
        env:
          ROCKSDB: 1
      - uses: technote-space/get-diff-action@v6.1.2
        if: steps.lint_long.outcome == 'skipped'
        with:
          PATTERNS: |
            **/*.go
            *.go
            !store/**
      - name: run linting (short)
        if: steps.lint_long.outcome == 'skipped' && env.GIT_DIFF
        run: |
          make lint
        env:
          GIT_DIFF: ${{ env.GIT_DIFF }}
          LINT_DIFF: 1
      - uses: technote-space/get-diff-action@v6.1.2
        if: steps.lint_long.outcome == 'skipped'
        with:
          PATTERNS: |
            store/**
      - name: run linting (short)
        if: steps.lint_long.outcome == 'skipped' && env.GIT_DIFF
        run: |
          make lint
        env:
          GIT_DIFF: ${{ env.GIT_DIFF }}
          LINT_DIFF: 1
          ROCKSDB: 1
