name: Lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: [no-failure, no-deprecations]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.49.0
          args: --exclude=nolintlint
            ${{ matrix.mode == 'no-deprecations' && '--exclude=SA1019:' || '' }}
            ${{ matrix.mode == 'no-failure' && '--issues-exit-code=0' || '' }}
